name: Flutter Integration Tests (Advanced)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Flutter version to test with'
        required: false
        default: '3.32.8'
        type: string

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        flutter_version: ['3.32.8', '3.32.0'] # Test with multiple Flutter versions
        include:
          - flutter_version: '3.32.8'
            display_name: 'Latest Stable'
          - flutter_version: '3.32.0'
            display_name: 'Previous Stable'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter_version }}
          channel: 'stable'
          
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            build
          key: ${{ runner.os }}-flutter-${{ matrix.flutter_version }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-${{ matrix.flutter_version }}-
            
      - name: Install dependencies
        run: flutter pub get
        
      - name: Verify Flutter setup
        run: |
          flutter doctor -v
          flutter --version
          
      - name: List available devices
        run: flutter devices
        
      - name: Setup Chrome Headless Environment
        run: |
          # Install Chrome and dependencies
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          
          # Add Google Chrome repository
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          
          # Install Google Chrome
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Verify Chrome installation
          google-chrome --version
          
          # Set up virtual display for headless operation
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 2
          
      - name: Run Integration Tests
        id: integration-tests
        run: |
          echo "Running integration tests with Flutter ${{ matrix.flutter_version }}"
          
          # Set environment variables for headless mode
          export CHROME_HEADLESS=true
          export DISPLAY=:99
          
          # Run tests with Chrome in headless mode
          flutter drive \
            --driver test_driver/integration_test.dart \
            --target integration_test/test.dart \
            -d chrome \
            --headless \
            --timeout 120 \
            --browser-name chrome \
            --verbose
        env:
          FLUTTER_TEST_TIMEOUT: 120
          FLUTTER_DRIVE_TIMEOUT: 120
          DISPLAY: :99
          
      - name: Capture screenshots on failure
        if: failure()
        run: |
          echo "Tests failed, capturing debug information..."
          flutter devices
          ps aux | grep flutter
          ps aux | grep chrome
          
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.flutter_version }}
          path: |
            build/
            .dart_tool/
            .flutter-plugins
            .flutter-plugins-dependencies
          retention-days: 30
          
      - name: Test Summary
        if: always()
        run: |
          echo "## Integration Test Results for ${{ matrix.display_name }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.integration-tests.outcome }}" == "success" ]; then
            echo "✅ **PASSED** - All integration tests completed successfully" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **FAILED** - Integration tests encountered errors" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Flutter Version:** ${{ matrix.flutter_version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Runner OS:** ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY 