name: Flutter Integration Tests (Simple & Reliable)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Verify Flutter setup
        run: flutter doctor
        
      - name: List available devices
        run: flutter devices
        
      - name: Run Integration Tests with Web Server
        run: |
          # Set environment variables
          export FLUTTER_TEST_TIMEOUT=120
          export FLUTTER_DRIVE_TIMEOUT=120
          
          # Run tests with web-server device (most reliable for CI)
          flutter drive \
            --driver test_driver/integration_test.dart \
            --target integration_test/test.dart \
            -d web-server \
            --headless \
            --timeout 120 \
            --web-port=8080 \
            --web-hostname=0.0.0.0
        env:
          FLUTTER_TEST_TIMEOUT: 120
          FLUTTER_DRIVE_TIMEOUT: 120
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/
            .dart_tool/
          retention-days: 7 